site_name: SpectralPlus
site_url: https://www.apitapestry.net/spectralplus/
use_directory_urls: true

nav:
  - Home: index.md
  - Overview: README.md

theme:
  name: material
  features:
    - navigation.expand
#    - navigation.sections
    - navigation.tracking
#    - navigation.top
#    - navigation.tabs
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  font:
    text: Inter
    code: Roboto Mono

extra_css:
  - extra.css

extra:
  generator: false
